#!/usr/bin/env sh

set -e

### A tidy $HOME is a tidy mind
# Obey XDG conventions;
export XDG_CONFIG_HOME="$HOME/.config";
[ -d "$XDG_CONFIG_HOME" ] || mkdir -p "$XDG_CONFIG_HOME"
export XDG_CACHE_HOME="$HOME/.cache";
[ -d "$XDG_CACHE_HOME" ] || mkdir -p "$XDG_CACHE_HOME"
export XDG_DATA_HOME="$HOME/.local/share";
[ -d "$XDG_DATA_HOME" ] || mkdir -p "$XDG_DATA_HOME"
export XDG_BIN_HOME="$HOME/.local/bin";
[ -d "$XDG_BIN_HOME" ] || mkdir -p "$XDG_BIN_HOME"

DOTFILES_PATH="$XDG_CONFIG_HOME/dotfiles"

XDGPathsArray=($XDG_CONFIG_HOME $XDG_CACHE_HOME $XDG_DATA_HOME $XDG_BIN_HOME)
for xdg_path in ${XDGPathsArray[*]}; do
  mkdir -p "$xdg_path"
done

if [ ! -d $DOTFILES_PATH ]; then
  git clone git@github.com:MuhmdRaouf/dotfiles.git $DOTFILES_PATH
else
  git clean -fdx && git reset --hard && git pull
fi

ConfigArray=("doom" "git" "skhd" "spacebar" "yabai" "zsh")
for conf in ${ConfigArray[*]}; do
  CONF_DOTFILES_PATH="$DOTFILES_PATH/$conf"
  CONF_XDG_PATH="$XDG_CONFIG_HOME/$conf"
  if [ ! -d $CONF_XDG_PATH ]; then
    ln -sf $CONF_DOTFILES_PATH $XDG_CONFIG_HOME
  fi
done

SymLinkArray=("gitconfig" "tmux.conf" "zshrc" "zshenv")
for conf in ${SymLinkArray[*]}; do
  ln -sf "$DOTFILES_PATH/$conf" "$HOME/.$conf"
done

ln -sf "$DOTFILES_PATH/bin" $XDG_BIN_HOME
