#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
#"""                               I Knew It!!                                """
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
alias iknewit-backend="cd $HOME/SnowflakeProjects/iknewit-backend/"
alias iknewit-mobile="cd $HOME/SnowflakeProjects/iknewit-mobile/"
alias iknewitdb="docker container start iknewitdb"
alias iknewitdb-stop="docker container stop iknewitdb"
alias iknewitdb-refresh="docker container rm -f iknewitdb; docker run --name iknewitdb --publish 5432:5432 --env POSTGRES_PASSWORD=password --detach postgres:12-alpine"
alias iknewitdb-shell="docker exec -it iknewitdb bash"
alias iknewitdb-db-shell="docker exec -it iknewitdb psql -U postgres"
#""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
