#!/usr/bin/env zsh

set -euo pipefail

# Apps Name
CHROME="Google Chrome"
EMACS="Emacs"
VSCODE="Visual Studio Code"
ITERM2="iTerm2"
DISCORD="Discord"
SLACK="Slack"
MAIL="Mail"
ZOHO="Zoho Mail - Desktop"
WHATSAPP="WhatsApp"
TELEGRAM="Telegram"
MAC_SYSTEM="System Preferences"

#space Labels
CHROME_SPACE="chrome"
EMACS_SPACE="emacs"
VSCODE_SPACE="vscode"
ITERM2_SPACE="iTerm"
WORK_SOCIAL_SPACE="workSocial"
MAIL_SPACE="mail"
SOCIAL_SPACE="social"

