#!/usr/bin/env zsh

set -euo pipefail

# functions
# Description:
#  wrapper function over yabao signal command
#  made for reusabilty
#
# Usage:
#  $ yabai_signal param1 param2 param3
#  * param1: app name
#  * param2: space name you want to use
#  * param3: app name you want to use
function yabai_signal() {
  app_pattern=${3:- }
  yabai --message signal --add event="$1" action="$2" app="$app_pattern"
}

# Description:
#  Keep space name dymanic even while moving
#  the app from space to another one
#
# Usage:
#  $ dynamic_space_naming param1 param2
#  * param1: app name
#  * param2: space name you want to use
function dynamic_space_naming() {
  anonymous() {
    if yabai -m query --windows --space |
        jq -e "map(select(.app == \"$1\" and .\"native-fullscreen\" == 1)) | length > 0" >/dev/null
    then
      yabai --message space --label "$2";
    fi
  }
  anonymous
}

# Description:
# create spaces based on the app will be launched
#
# Usage:
#  $ create_space_with_spacfic_label param1 param2
#  * param1: app name
#  * param2: space name you want to create
create_space_with_spacfic_label() {
  anonymous() {
    if yabai --message query --spaces | jq -e "map(select(.label == \"$2\")) | length == 0" >/dev/null
    then
      yabai --message space --create
      SPACE_INDEX=$(yabai --message query --spaces --display | jq "map(select(.\"native-fullscreen\" == 0))[-1].index")
      yabai --message space $SPACE_INDEX --label "$2"
    fi
    yabai --message rule --add app="^${1}$" space="$2"
  }
  anonymous
}

# Description:
# delete the space if it has no windows left
#
# Usage:
#  $ terminate_empty_spaces
terminate_empty_spaces(){
  anonymous() {
    DISPLAY1_SPACE=$(yabai --message query --spaces --display 1 | jq "map(select(.\"native-fullscreen\" == 0 and .label == \"\"))[0].index")
    DISPLAY2_SPACE=$(yabai --message query --spaces --display 2 | jq "map(select(.\"native-fullscreen\" == 0 and .label == \"\"))[0].index")
    if yabai --message query --windows --space | jq -e "length == 0" >/dev/null &&
    then
      yabai --message space --destroy
    fi
  }
  anonymous
}

