#!/usr/bin/env zsh

set -euo pipefail

# global settings
yabai --message config mouse_follows_focus          off
yabai --message config focus_follows_mouse          off
yabai --message config window_placement             second_child
yabai --message config window_topmost               on
yabai --message config window_shadow                on
yabai --message config window_opacity               on
yabai --message config active_window_opacity        1.0
yabai --message config normal_window_opacity        0.75
yabai --message config window_border                off
yabai --message config window_border_width          6
yabai --message config active_window_border_color   0xff61afef
yabai --message config normal_window_border_color   0xff282c34
yabai --message config insert_feedback_color        0xffe06c75
yabai --message config split_ratio                  0.50
yabai --message config auto_balance                 off
yabai --message config mouse_modifier               fn
yabai --message config mouse_action1                move
yabai --message config mouse_action2                resize
yabai --message config mouse_drop_action            swap


# general space settings
yabai --message config layout                       bsp
yabai --message config top_padding                  32
yabai --message config bottom_padding               06
yabai --message config left_padding                 06
yabai --message config right_padding                06
yabai --message config window_gap                   06

echo "yabai settings loaded.."

