#!/usr/bin/env zsh

set -euo pipefail

source "$XDG_CONFIG_HOME/yabai/helper_functions"
source "$XDG_CONFIG_HOME/yabai/constants"

# Main Apps
yabai_signal space_changed          "${functions[dynamic_space_naming]}            \"$CHROME\"   $CHROME_SPACE"      "$CHROME"
yabai_signal space_changed          "${functions[dynamic_space_naming]}            \"$EMACS\"    $EMACS_SPACE"       "$EMACS"
yabai_signal space_changed          "${functions[dynamic_space_naming]}            \"$ITERM2\"   $ITERM2_SPACE"      "$ITERM2"
yabai_signal space_changed          "${functions[dynamic_space_naming]}            \"$VSCODE\"   $VSCODE_SPACE"      "$VSCODE"

yabai_signal application_activated  "${functions[dynamic_space_naming]}            \"$CHROME\"   $CHROME_SPACE"      "$CHROME"
yabai_signal application_activated  "${functions[dynamic_space_naming]}            \"$EMACS\"    $EMACS_SPACE"       "$EMACS"
yabai_signal application_activated  "${functions[dynamic_space_naming]}            \"$ITERM2\"   $ITERM2_SPACE"      "$ITERM2"
yabai_signal application_activated  "${functions[dynamic_space_naming]}            \"$VSCODE\"   $VSCODE_SPACE"      "$VSCODE"

# Productivity
yabai_signal application_activated  "${functions[create_space_with_spacfic_label]} \"$DISCORD\"  $WORK_SOCIAL_SPACE" "$DISCORD"
yabai_signal application_activated  "${functions[create_space_with_spacfic_label]} \"$SLACK\"    $WORK_SOCIAL_SPACE" "$SLACK"
yabai_signal application_activated  "${functions[create_space_with_spacfic_label]} \"$MAIL\"     $MAIL_SPACE"        "$MAIL"
yabai_signal application_activated  "${functions[create_space_with_spacfic_label]} \"$ZOHO\"     $MAIL_SPACE"        "$ZOHO"
yabai_signal application_activated  "${functions[create_space_with_spacfic_label]} \"$WHATSAPP\" $SOCIAL_SPACE"      "$WHATSAPP"
yabai_signal application_activated  "${functions[create_space_with_spacfic_label]} \"$TELEGRAM\" $SOCIAL_SPACE"      "$TELEGRAM"

# Clean spaces
yabai_signal application_terminated "${functions[terminate_empty_spaces]}"
yabai_signal window_destroyed       "${functions[terminate_empty_spaces]}"

echo "yabai signals loaded.."

