services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    networks:
      - app-private
    environment:
      TZ: "Africa/Cairo"
      WATCHTOWER_DEBUG: true
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
