#!/usr/bin/env zsh

set -euo pipefail

spacebar --message config position           top
spacebar --message config height             26
spacebar --message config text_font          "Hasklug Nerd Font:Medium Italic:12.0"
spacebar --message config icon_font          "Hasklug Nerd Font:Medium Italic:12.0"
spacebar --message config background_color   0xff202020
spacebar --message config foreground_color   0xffa8a8a8
spacebar --message config space_icon_color   0xff458588
spacebar --message config power_icon_color   0xffcd950c
spacebar --message config battery_icon_color 0xffd75f5f
spacebar --message config dnd_icon_color     0xffa8a8a8
spacebar --message config clock_icon_color   0xffa8a8a8
# spacebar --message config status_bar_space_icon_strip          
spacebar --message config space_icon_strip   I II III IV V VI VII VIII IX X
spacebar --message config power_icon_strip    
spacebar --message config space_icon         
spacebar --message config clock_icon         
spacebar --message config dnd_icon           
spacebar --message config clock_format       "%A %d %B, %Y %I:%M%p"

echo "spacebar configuration loaded.."

